services:
  mysql:
    container_name: 'seiornote-db'
    image: 'mysql:8.0.29'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'company'
    restart: always

    